In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
dataset = pd.read_csv("stock_market.csv")

In [3]:
dataset.head()

,open,high,low,close,adjclose,volume,RSIadjclose15,RSIvolume15,RSIadjclose25,RSIvolume25,...,high-15,K-15,D-15,stochastic-k-15,stochastic-d-15,stochastic-kd-15,volumenrelativo,diff,INCREMENTO,TARGET
0,13.81,14.120,13.61,14.10,14.10,74700,47.575179,48.098729,46.186849,48.801565,...,15.09,57.142875,47.186159,57.142875,47.186159,9.956716,0.644521,-0.06,-0.423732,0
1,14.10,14.320,14.05,14.18,14.18,71400,48.459097,47.832464,46.721997,48.655966,...,14.76,70.707082,59.066871,70.707082,59.066871,11.640211,0.616048,0.21,1.503221,0
2,14.12,14.347,13.79,13.82,13.82,89700,44.815889,49.493682,44.641044,49.525845,...,14.76,52.525237,60.125065,52.525237,60.125065,-7.599827,0.773943,0.51,3.831707,0
3,14.01,14.250,13.94,14.11,14.11,84800,48.178500,49.045623,46.635466,49.292914,...,14.76,67.171696,63.468005,67.171696,63.468005,3.703691,0.731665,0.06,0.427049,0
4,14.14,14.140,13.53,13.86,13.86,315400,45.611408,65.015137,45.174001,58.793541,...,14.76,52.127632,57.274855,52.127632,57.274855,-5.147223,2.721311,0.75,5.720824,1

In [5]:
# Keep only numeric columns
data = dataset.select_dtypes(include=['float64', 'int64'])

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4204 entries, 0 to 4203
Columns: 1283 entries, open to TARGET
dtypes: float64(1280), int64(3)
memory usage: 41.2 MB

In [14]:
data1 = dataset.copy()
cols_to_drop = ['date','open','low','high','close','ticker']
data = data1.drop(columns=[c for c in cols_to_drop if c in data1.columns])
data.head()

,adjclose,volume,RSIadjclose15,RSIvolume15,RSIadjclose25,RSIvolume25,RSIadjclose50,RSIvolume50,MACDadjclose15,MACDvolume15,...,high-15,K-15,D-15,stochastic-k-15,stochastic-d-15,stochastic-kd-15,volumenrelativo,diff,INCREMENTO,TARGET
0,14.10,74700,47.575179,48.098729,46.186849,48.801565,45.763321,49.242150,-0.394488,596.011511,...,15.09,57.142875,47.186159,57.142875,47.186159,9.956716,0.644521,-0.06,-0.423732,0
1,14.18,71400,48.459097,47.832464,46.721997,48.655966,46.064456,49.166315,-0.339280,-1528.965232,...,14.76,70.707082,59.066871,70.707082,59.066871,11.640211,0.616048,0.21,1.503221,0
2,13.82,89700,44.815889,49.493682,44.641044,49.525845,44.919239,49.605477,-0.320866,-1717.140972,...,14.76,52.525237,60.125065,52.525237,60.125065,-7.599827,0.773943,0.51,3.831707,0
3,14.11,84800,48.178500,49.045623,46.635466,49.292914,46.022313,49.488662,-0.279657,-2235.743404,...,14.76,67.171696,63.468005,67.171696,63.468005,3.703691,0.731665,0.06,0.427049,0
4,13.86,315400,45.611408,65.015137,45.174001,58.793541,45.225594,54.620415,-0.264120,15772.702210,...,14.76,52.127632,57.274855,52.127632,57.274855,-5.147223,2.721311,0.75,5.720824,1

In [15]:
import numpy as np

# Count how many infinite values are in the dataset
np.isinf(data).sum().sum()

np.int64(558)

In [16]:
# Replace infinity with NaN
data.replace([np.inf, -np.inf], np.nan, inplace=True)

# Drop any rows with NaN
data = data.dropna()

In [17]:
data = data.clip(-1e10, 1e10)

In [18]:
X = data.drop("TARGET", axis=1)
y = data["TARGET"]

In [19]:
from sklearn.preprocessing import StandardScaler

scaler =StandardScaler()
X_Scaled = scaler.fit_transform(X)

In [20]:
X.head()

,adjclose,volume,RSIadjclose15,RSIvolume15,RSIadjclose25,RSIvolume25,RSIadjclose50,RSIvolume50,MACDadjclose15,MACDvolume15,...,low-15,high-15,K-15,D-15,stochastic-k-15,stochastic-d-15,stochastic-kd-15,volumenrelativo,diff,INCREMENTO
0,14.10,74700,47.575179,48.098729,46.186849,48.801565,45.763321,49.242150,-0.394488,596.011511,...,12.78,15.09,57.142875,47.186159,57.142875,47.186159,9.956716,0.644521,-0.06,-0.423732
1,14.18,71400,48.459097,47.832464,46.721997,48.655966,46.064456,49.166315,-0.339280,-1528.965232,...,12.78,14.76,70.707082,59.066871,70.707082,59.066871,11.640211,0.616048,0.21,1.503221
2,13.82,89700,44.815889,49.493682,44.641044,49.525845,44.919239,49.605477,-0.320866,-1717.140972,...,12.78,14.76,52.525237,60.125065,52.525237,60.125065,-7.599827,0.773943,0.51,3.831707
3,14.11,84800,48.178500,49.045623,46.635466,49.292914,46.022313,49.488662,-0.279657,-2235.743404,...,12.78,14.76,67.171696,63.468005,67.171696,63.468005,3.703691,0.731665,0.06,0.427049
4,13.86,315400,45.611408,65.015137,45.174001,58.793541,45.225594,54.620415,-0.264120,15772.702210,...,12.88,14.76,52.127632,57.274855,52.127632,57.274855,-5.147223,2.721311,0.75,5.720824

In [21]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X_Scaled,y,test_size=0.2,random_state=42)

In [22]:
X_train.shape

(2966, 1278)

In [23]:
X_test.shape

(742, 1278)

In [24]:
y_train.shape

(2966,)

In [25]:
y_test.shape

(742,)

In [26]:
from sklearn.linear_model import LinearRegression

regression = LinearRegression()
regression.fit(X_train,y_train)

y_pred = regression.predict(X_test)

In [27]:
from sklearn.metrics import mean_absolute_error,r2_score

mae = mean_absolute_error(y_test,y_pred)
rmse = np.sqrt(mae)

print("Mean absolute error",mae)
print("Root mean squared error",rmse)

Mean absolute error 109.11466780823261
Root mean squared error 10.445796657423148

In [28]:
score = r2_score(y_test,y_pred)
print("R2 Score is: ",score)

R2 Score is:  -32886343.09868668

In [29]:
# Compute correlation with TARGET
corr = data.corr()['TARGET'].abs()

# Select features with correlation > 0.05 (adjust threshold)
important_features = corr[corr>0.05].index.to_list()

# Remove TARGET from feature list
important_features.remove('TARGET')

# New X with selected features
X_Selected = data[important_features]
y = data['TARGET']

In [30]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_Scaled = scaler.fit_transform(X_Selected)

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_Scaled, y, test_size=0.2, shuffle=False
)

In [32]:
from sklearn.linear_model import Ridge

ridge = Ridge(alpha=1.0)  # alpha is regularization strength
ridge.fit(X_train, y_train)

y_pred = ridge.predict(X_test)

In [33]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("Improved Linear Regression Metrics (Ridge):")
print("MAE  :", mae)
print("RMSE :", rmse)
print("R²   :", r2)

Improved Linear Regression Metrics (Ridge):
MAE  : 0.327120376724162
RMSE : 0.6021675002727316
R²   : -1.2824860655745685